;------------------------------------------------------------
;                                  ___ ___ _   
;  ___ ___ ___ ___ ___       _____|  _| . | |_ 
; |  _| . |_ -|  _| . |     |     | . | . | '_|
; |_| |___|___|___|___|_____|_|_|_|___|___|_,_| 
;                     |_____|       firmware v1                 
;------------------------------------------------------------
; Copyright (c)2019 Ross Bamford
; See top-level LICENSE.md for licence information.
;
; Critical sections
;------------------------------------------------------------
    section .text

CRITICAL_BEGIN::
    or.w    #$0700,SR
    rts

CRITICAL_END::
    and.w   #$F0FF,SR
    rts
