CC=m68k-elf-gcc
LD=m68k-elf-ld

CFLAGS=-std=c11 -Wall -Werror -Wpedantic -Iinclude -O3 -ffreestanding -nostartfiles
OBJFILES=zheaders.o znumbers.o zserial.o crc16.o crc32.o

all: $(OBJFILES)

%.o: %.c
	$(CC) $(CFLAGS) -DZEMBEDDED -c -o $@ $<

clean:
	rm -f *.o rz

