# Make sdfat_menu program for rosco_m68k
#
# Copyright (c) 2020-2022 Xark and contributors
# MIT LICENSE

-include $(ROSCO_M68K_DIR)/code/software/rosco-software.mk

ROSCODE1.BIN: sdfat_menu.bin
	cp $< $@

